//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSwissKnife.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveTabId {
            get {
                return ((string)(this["ActiveTabId"]));
            }
            set {
                this["ActiveTabId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public long SplitSize {
            get {
                return ((long)(this["SplitSize"]));
            }
            set {
                this["SplitSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MB")]
        public global::FileSwissKnife.Utils.UnitsManagement.SIUnit SplitUnit {
            get {
                return ((global::FileSwissKnife.Utils.UnitsManagement.SIUnit)(this["SplitUnit"]));
            }
            set {
                this["SplitUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SelectedHashes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SelectedHashes"]));
            }
            set {
                this["SelectedHashes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AfterExt")]
        public global::ElMariachi.FS.Tools.Splitting.NumPos SplitNumPos {
            get {
                return ((global::ElMariachi.FS.Tools.Splitting.NumPos)(this["SplitNumPos"]));
            }
            set {
                this["SplitNumPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".part")]
        public string SplitNumPrefix {
            get {
                return ((string)(this["SplitNumPrefix"]));
            }
            set {
                this["SplitNumPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SplitPadWithZeros {
            get {
                return ((bool)(this["SplitPadWithZeros"]));
            }
            set {
                this["SplitPadWithZeros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public long SplitStartNumber {
            get {
                return ((long)(this["SplitStartNumber"]));
            }
            set {
                this["SplitStartNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitLastDir {
            get {
                return ((string)(this["SplitLastDir"]));
            }
            set {
                this["SplitLastDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitNumSuffix {
            get {
                return ((string)(this["SplitNumSuffix"]));
            }
            set {
                this["SplitNumSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JoinLastDir {
            get {
                return ((string)(this["JoinLastDir"]));
            }
            set {
                this["JoinLastDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ForcedLanguage {
            get {
                return ((string)(this["ForcedLanguage"]));
            }
            set {
                this["ForcedLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4194304")]
        public int JoinBufferSize {
            get {
                return ((int)(this["JoinBufferSize"]));
            }
            set {
                this["JoinBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4194304")]
        public int SplitBufferSize {
            get {
                return ((int)(this["SplitBufferSize"]));
            }
            set {
                this["SplitBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4194304")]
        public int HashBufferSize {
            get {
                return ((int)(this["HashBufferSize"]));
            }
            set {
                this["HashBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveTheme {
            get {
                return ((string)(this["ActiveTheme"]));
            }
            set {
                this["ActiveTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool JoinGuessMissingFiles {
            get {
                return ((bool)(this["JoinGuessMissingFiles"]));
            }
            set {
                this["JoinGuessMissingFiles"] = value;
            }
        }
    }
}
